In [2]:
import csv
import pandas as pd
import os

In [3]:
PATH = 'D:/Users/25052288840/Downloads/FIA_data_mining/Aula 14 - Regressão Logística'

In [4]:
os.listdir(PATH)

['.ipynb_checkpoints',
 'Regressão Logística. Material Professor Herbert Kimura.pdf',
 'RF-Admissao.csv',
 'RF-Admissao.ods',
 'RF_admissao.ipynb']

In [5]:
filename = os.path.join(PATH, 'RF-Admissao.csv')
with open(filename) as file:
    reader = csv.reader(file)
    linhas = [row for row in reader]

In [6]:
linhas

[['obs', 'admit', 'gre', 'gpa', 'rank'],
 ['1', '0', '380', '3.609999895', '3'],
 ['2', '1', '660', '3.670000076', '3'],
 ['3', '1', '800', '4', '1'],
 ['4', '1', '640', '3.190000057', '4'],
 ['5', '0', '520', '2.930000067', '4'],
 ['6', '1', '760', '3', '2'],
 ['7', '1', '560', '2.980000019', '1'],
 ['8', '0', '400', '3.079999924', '2'],
 ['9', '1', '540', '3.390000105', '3'],
 ['10', '0', '700', '3.920000076', '2'],
 ['11', '0', '800', '4', '4'],
 ['12', '0', '440', '3.220000029', '1'],
 ['13', '1', '760', '4', '1'],
 ['14', '0', '700', '3.079999924', '2'],
 ['15', '1', '700', '4', '1'],
 ['16', '0', '480', '3.440000057', '3'],
 ['17', '0', '780', '3.869999886', '4'],
 ['18', '0', '360', '2.559999943', '3'],
 ['19', '0', '800', '3.75', '2'],
 ['20', '1', '540', '3.809999943', '1'],
 ['21', '0', '500', '3.170000076', '3'],
 ['22', '1', '660', '3.630000114', '2'],
 ['23', '0', '600', '2.819999933', '4'],
 ['24', '0', '680', '3.190000057', '4'],
 ['25', '1', '760', '3.349999905', '2'],
 ['26', '1', '800', '3.660000086', '1'],
 ['27', '1', '620', '3.609999895', '1'],
 ['28', '1', '520', '3.74000001', '4'],
 ['29', '1', '780', '3.220000029', '2'],
 ['30', '0', '520', '3.289999962', '1'],
 ['31', '0', '540', '3.779999971', '4'],
 ['32', '0', '760', '3.349999905', '3'],
 ['33', '0', '600', '3.400000095', '3'],
 ['34', '1', '800', '4', '3'],
 ['35', '0', '360', '3.140000105', '1'],
 ['36', '0', '400', '3.049999952', '2'],
 ['37', '0', '580', '3.25', '1'],
 ['38', '0', '520', '2.900000095', '3'],
 ['39', '1', '500', '3.130000114', '2'],
 ['40', '1', '520', '2.680000067', '3'],
 ['41', '0', '560', '2.420000076', '2'],
 ['42', '1', '580', '3.319999933', '2'],
 ['43', '1', '600', '3.150000095', '2'],
 ['44', '0', '500', '3.309999943', '3'],
 ['45', '0', '700', '2.940000057', '2'],
 ['46', '1', '460', '3.450000048', '3'],
 ['47', '1', '580', '3.460000038', '2'],
 ['48', '0', '500', '2.970000029', '4'],
 ['49', '0', '440', '2.480000019', '4'],
 ['50', '0', '400', '3.349999905', '3'],
 ['51', '0', '640', '3.859999895', '3'],
 ['52', '0', '440', '3.130000114', '4'],
 ['53', '0', '740', '3.369999886', '4'],
 ['54', '1', '680', '3.269999981', '2'],
 ['55', '0', '660', '3.339999914', '3'],
 ['56', '1', '740', '4', '3'],
 ['57', '0', '560', '3.190000057', '3'],
 ['58', '0', '380', '2.940000057', '3'],
 ['59', '0', '400', '3.650000095', '2'],
 ['60', '0', '600', '2.819999933', '4'],
 ['61', '1', '620', '3.180000067', '2'],
 ['62', '0', '560', '3.319999933', '4'],
 ['63', '0', '640', '3.670000076', '3'],
 ['64', '1', '680', '3.849999905', '3'],
 ['65', '0', '580', '4', '3'],
 ['66', '0', '600', '3.589999914', '2'],
 ['67', '0', '740', '3.619999886', '4'],
 ['68', '0', '620', '3.299999952', '1'],
 ['69', '0', '580', '3.690000057', '1'],
 ['70', '0', '800', '3.730000019', '1'],
 ['71', '0', '640', '4', '3'],
 ['72', '0', '300', '2.920000076', '4'],
 ['73', '0', '480', '3.390000105', '4'],
 ['74', '0', '580', '4', '2'],
 ['75', '0', '720', '3.450000048', '4'],
 ['76', '0', '720', '4', '3'],
 ['77', '0', '560', '3.359999895', '3'],
 ['78', '1', '800', '4', '3'],
 ['79', '0', '540', '3.119999886', '1'],
 ['80', '1', '620', '4', '1'],
 ['81', '0', '700', '2.900000095', '4'],
 ['82', '0', '620', '3.069999933', '2'],
 ['83', '0', '500', '2.710000038', '2'],
 ['84', '0', '380', '2.910000086', '4'],
 ['85', '1', '500', '3.599999905', '3'],
 ['86', '0', '520', '2.980000019', '2'],
 ['87', '0', '600', '3.319999933', '2'],
 ['88', '0', '600', '3.480000019', '2'],
 ['89', '0', '700', '3.279999971', '1'],
 ['90', '1', '660', '4', '2'],
 ['91', '0', '700', '3.829999924', '2'],
 ['92', '1', '720', '3.640000105', '1'],
 ['93', '0', '800', '3.900000095', '2'],
 ['94', '0', '580', '2.930000067', '2'],
 ['95', '1', '660', '3.440000057', '2'],
 ['96', '0', '660', '3.329999924', '2'],
 ['97', '0', '640', '3.519999981', '4'],
 ['98', '0', '480', '3.569999933', '2'],
 ['99', '0', '700', '2.880000114', '2'],
 ['100', '0', '400', '3.309999943', '3'],
 ['101', '0', '340', '3.150000095', '3'],
 ['102', '0', '580', '3.569999933', '3'],
 ['103', '0', '380', '3.329999924', '4'],
 ['104', '0', '540', '3.940000057', '3'],
 ['105', '1', '660', '3.950000048', '2'],
 ['106', '1', '740', '2.970000029', '2'],
 ['107', '1', '700', '3.559999943', '1'],
 ['108', '0', '480', '3.130000114', '2'],
 ['109', '0', '400', '2.930000067', '3'],
 ['110', '0', '480', '3.450000048', '2'],
 ['111', '0', '680', '3.079999924', '4'],
 ['112', '0', '420', '3.410000086', '4'],
 ['113', '0', '360', '3', '3'],
 ['114', '0', '600', '3.220000029', '1'],
 ['115', '0', '720', '3.839999914', '3'],
 ['116', '0', '620', '3.99000001', '3'],
 ['117', '1', '440', '3.450000048', '2'],
 ['118', '0', '700', '3.720000029', '2'],
 ['119', '1', '800', '3.700000048', '1'],
 ['120', '0', '340', '2.920000076', '3'],
 ['121', '1', '520', '3.74000001', '2'],
 ['122', '1', '480', '2.670000076', '2'],
 ['123', '0', '520', '2.849999905', '3'],
 ['124', '0', '500', '2.980000019', '3'],
 ['125', '0', '720', '3.880000114', '3'],
 ['126', '0', '540', '3.380000114', '4'],
 ['127', '1', '600', '3.539999962', '1'],
 ['128', '0', '740', '3.74000001', '4'],
 ['129', '0', '540', '3.190000057', '2'],
 ['130', '0', '460', '3.150000095', '4'],
 ['131', '1', '620', '3.170000076', '2'],
 ['132', '0', '640', '2.789999962', '2'],
 ['133', '0', '580', '3.400000095', '2'],
 ['134', '0', '500', '3.079999924', '3'],
 ['135', '0', '560', '2.950000048', '2'],
 ['136', '0', '500', '3.569999933', '3'],
 ['137', '0', '560', '3.329999924', '4'],
 ['138', '0', '700', '4', '3'],
 ['139', '0', '620', '3.400000095', '2'],
 ['140', '1', '600', '3.579999924', '1'],
 ['141', '0', '640', '3.930000067', '2'],
 ['142', '1', '700', '3.519999981', '4'],
 ['143', '0', '620', '3.940000057', '4'],
 ['144', '0', '580', '3.400000095', '3'],
 ['145', '0', '580', '3.400000095', '4'],
 ['146', '0', '380', '3.430000067', '3'],
 ['147', '0', '480', '3.400000095', '2'],
 ['148', '0', '560', '2.710000038', '3'],
 ['149', '1', '480', '2.910000086', '1'],
 ['150', '0', '740', '3.309999943', '1'],
 ['151', '1', '800', '3.74000001', '1'],
 ['152', '0', '400', '3.380000114', '2'],
 ['153', '1', '640', '3.940000057', '2'],
 ['154', '0', '580', '3.460000038', '3'],
 ['155', '0', '620', '3.690000057', '3'],
 ['156', '1', '580', '2.859999895', '4'],
 ['157', '0', '560', '2.519999981', '2'],
 ['158', '1', '480', '3.579999924', '1'],
 ['159', '0', '660', '3.49000001', '2'],
 ['160', '0', '700', '3.819999933', '3'],
 ['161', '0', '600', '3.130000114', '2'],
 ['162', '0', '640', '3.5', '2'],
 ['163', '1', '700', '3.559999943', '2'],
 ['164', '0', '520', '2.730000019', '2'],
 ['165', '0', '580', '3.299999952', '2'],
 ['166', '0', '700', '4', '1'],
 ['167', '0', '440', '3.24000001', '4'],
 ['168', '0', '720', '3.769999981', '3'],
 ['169', '0', '500', '4', '3'],
 ['170', '0', '600', '3.619999886', '3'],
 ['171', '0', '400', '3.50999999', '3'],
 ['172', '0', '540', '2.809999943', '3'],
 ['173', '0', '680', '3.480000019', '3'],
 ['174', '1', '800', '3.430000067', '2'],
 ['175', '0', '500', '3.529999971', '4'],
 ['176', '1', '620', '3.369999886', '2'],
 ['177', '0', '520', '2.619999886', '2'],
 ['178', '1', '620', '3.230000019', '3'],
 ['179', '0', '620', '3.329999924', '3'],
 ['180', '0', '300', '3.00999999', '3'],
 ['181', '0', '620', '3.779999971', '3'],
 ['182', '0', '500', '3.880000114', '4'],
 ['183', '0', '700', '4', '2'],
 ['184', '1', '540', '3.839999914', '2'],
 ['185', '0', '500', '2.789999962', '4'],
 ['186', '0', '800', '3.599999905', '2'],
 ['187', '0', '560', '3.609999895', '3'],
 ['188', '0', '580', '2.880000114', '2'],
 ['189', '0', '560', '3.069999933', '2'],
 ['190', '0', '500', '3.349999905', '2'],
 ['191', '1', '640', '2.940000057', '2'],
 ['192', '0', '800', '3.539999962', '3'],
 ['193', '0', '640', '3.75999999', '3'],
 ['194', '0', '380', '3.589999914', '4'],
 ['195', '1', '600', '3.470000029', '2'],
 ['196', '0', '560', '3.589999914', '2'],
 ['197', '0', '660', '3.069999933', '3'],
 ['198', '1', '400', '3.230000019', '4'],
 ['199', '0', '600', '3.630000114', '3'],
 ['200', '0', '580', '3.769999981', '4'],
 ['201', '0', '800', '3.309999943', '3'],
 ['202', '1', '580', '3.200000048', '2'],
 ['203', '1', '700', '4', '1'],
 ['204', '0', '420', '3.920000076', '4'],
 ['205', '1', '600', '3.890000105', '1'],
 ['206', '1', '780', '3.799999952', '3'],
 ['207', '0', '740', '3.539999962', '1'],
 ['208', '1', '640', '3.630000114', '1'],
 ['209', '0', '540', '3.160000086', '3'],
 ['210', '0', '580', '3.5', '2'],
 ['211', '0', '740', '3.339999914', '4'],
 ['212', '0', '580', '3.019999981', '2'],
 ['213', '0', '460', '2.869999886', '2'],
 ['214', '0', '640', '3.380000114', '3'],
 ['215', '1', '600', '3.559999943', '2'],
 ['216', '1', '660', '2.910000086', '3'],
 ['217', '0', '340', '2.900000095', '1'],
 ['218', '1', '460', '3.640000105', '1'],
 ['219', '0', '460', '2.980000019', '1'],
 ['220', '1', '560', '3.589999914', '2'],
 ['221', '0', '540', '3.279999971', '3'],
 ['222', '0', '680', '3.99000001', '3'],
 ['223', '1', '480', '3.019999981', '1'],
 ['224', '0', '800', '3.470000029', '3'],
 ['225', '0', '800', '2.900000095', '2'],
 ['226', '1', '720', '3.5', '3'],
 ['227', '0', '620', '3.579999924', '2'],
 ['228', '0', '540', '3.019999981', '4'],
 ['229', '0', '480', '3.430000067', '2'],
 ['230', '1', '720', '3.420000076', '2'],
 ['231', '0', '580', '3.289999962', '4'],
 ['232', '0', '600', '3.279999971', '3'],
 ['233', '0', '380', '3.380000114', '2'],
 ['234', '0', '420', '2.670000076', '3'],
 ['235', '1', '800', '3.529999971', '1'],
 ['236', '0', '620', '3.049999952', '2'],
 ['237', '1', '660', '3.49000001', '2'],
 ['238', '0', '480', '4', '2'],
 ['239', '0', '500', '2.859999895', '4'],
 ['240', '0', '700', '3.450000048', '3'],
 ['241', '0', '440', '2.75999999', '2'],
 ['242', '1', '520', '3.809999943', '1'],
 ['243', '1', '680', '2.960000038', '3'],
 ['244', '0', '620', '3.220000029', '2'],
 ['245', '0', '540', '3.039999962', '1'],
 ['246', '0', '800', '3.910000086', '3'],
 ['247', '0', '680', '3.339999914', '2'],
 ['248', '0', '440', '3.170000076', '2'],
 ['249', '0', '680', '3.640000105', '3'],
 ['250', '0', '640', '3.730000019', '3'],
 ['251', '0', '660', '3.309999943', '4'],
 ['252', '0', '620', '3.210000038', '4'],
 ['253', '1', '520', '4', '2'],
 ['254', '1', '540', '3.549999952', '4'],
 ['255', '1', '740', '3.519999981', '4'],
 ['256', '0', '640', '3.349999905', '3'],
 ['257', '1', '520', '3.299999952', '2'],
 ['258', '1', '620', '3.950000048', '3'],
 ['259', '0', '520', '3.50999999', '2'],
 ['260', '0', '640', '3.809999943', '2'],
 ['261', '0', '680', '3.109999895', '2'],
 ['262', '0', '440', '3.150000095', '2'],
 ['263', '1', '520', '3.190000057', '3'],
 ['264', '1', '620', '3.950000048', '3'],
 ['265', '1', '520', '3.900000095', '3'],
 ['266', '0', '380', '3.339999914', '3'],
 ['267', '0', '560', '3.24000001', '4'],
 ['268', '1', '600', '3.640000105', '3'],
 ['269', '1', '680', '3.460000038', '2'],
 ['270', '0', '500', '2.809999943', '3'],
 ['271', '1', '640', '3.950000048', '2'],
 ['272', '0', '540', '3.329999924', '3'],
 ['273', '1', '680', '3.670000076', '2'],
 ['274', '0', '660', '3.319999933', '1'],
 ['275', '0', '520', '3.119999886', '2'],
 ['276', '1', '600', '2.980000019', '2'],
 ['277', '0', '460', '3.769999981', '3'],
 ['278', '1', '580', '3.579999924', '1'],
 ['279', '1', '680', '3', '4'],
 ['280', '1', '660', '3.140000105', '2'],
 ['281', '0', '660', '3.940000057', '2'],
 ['282', '0', '360', '3.269999981', '3'],
 ['283', '0', '660', '3.450000048', '4'],
 ['284', '0', '520', '3.099999905', '4'],
 ['285', '1', '440', '3.390000105', '2'],
 ['286', '0', '600', '3.309999943', '4'],
 ['287', '1', '800', '3.220000029', '1'],
 ['288', '1', '660', '3.700000048', '4'],
 ['289', '0', '800', '3.150000095', '4'],
 ['290', '0', '420', '2.25999999', '4'],
 ['291', '1', '620', '3.450000048', '2'],
 ['292', '0', '800', '2.779999971', '2'],
 ['293', '0', '680', '3.700000048', '2'],
 ['294', '0', '800', '3.970000029', '1'],
 ['295', '0', '480', '2.549999952', '1'],
 ['296', '0', '520', '3.25', '3'],
 ['297', '0', '560', '3.160000086', '1'],
 ['298', '0', '460', '3.069999933', '2'],
 ['299', '0', '540', '3.5', '2'],
 ['300', '0', '720', '3.400000095', '3'],
 ['301', '0', '640', '3.299999952', '2'],
 ['302', '1', '660', '3.599999905', '3'],
 ['303', '1', '400', '3.150000095', '2'],
 ['304', '1', '680', '3.980000019', '2'],
 ['305', '0', '220', '2.829999924', '3'],
 ['306', '0', '580', '3.460000038', '4'],
 ['307', '1', '540', '3.170000076', '1'],
 ['308', '0', '580', '3.50999999', '2'],
 ['309', '0', '540', '3.130000114', '2'],
 ['310', '0', '440', '2.980000019', '3'],
 ['311', '0', '560', '4', '3'],
 ['312', '0', '660', '3.670000076', '2'],
 ['313', '0', '660', '3.769999981', '3'],
 ['314', '1', '520', '3.650000095', '4'],
 ['315', '0', '540', '3.460000038', '4'],
 ['316', '1', '300', '2.839999914', '2'],
 ['317', '1', '340', '3', '2'],
 ['318', '1', '780', '3.630000114', '4'],
 ['319', '1', '480', '3.710000038', '4'],
 ['320', '0', '540', '3.279999971', '1'],
 ['321', '0', '460', '3.140000105', '3'],
 ['322', '0', '460', '3.579999924', '2'],
 ['323', '0', '500', '3.00999999', '4'],
 ['324', '0', '420', '2.690000057', '2'],
 ['325', '0', '520', '2.700000048', '3'],
 ['326', '0', '680', '3.900000095', '1'],
 ['327', '0', '680', '3.309999943', '2'],
 ['328', '1', '560', '3.480000019', '2'],
 ['329', '0', '580', '3.339999914', '2'],
 ['330', '0', '500', '2.930000067', '4'],
 ['331', '0', '740', '4', '3'],
 ['332', '0', '660', '3.589999914', '3'],
 ['333', '0', '420', '2.960000038', '1'],
 ['334', '0', '560', '3.430000067', '3'],
 ['335', '1', '460', '3.640000105', '3'],
 ['336', '1', '620', '3.710000038', '1'],
 ['337', '0', '520', '3.150000095', '3'],
 ['338', '0', '620', '3.089999914', '4'],
 ['339', '0', '540', '3.200000048', '1'],
 ['340', '1', '660', '3.470000029', '3'],
 ['341', '0', '500', '3.230000019', '4'],
 ['342', '1', '560', '2.650000095', '3'],
 ['343', '0', '500', '3.950000048', '4'],
 ['344', '0', '580', '3.059999943', '2'],
 ['345', '0', '520', '3.349999905', '3'],
 ['346', '0', '500', '3.029999971', '3'],
 ['347', '0', '600', '3.349999905', '2'],
 ['348', '0', '580', '3.799999952', '2'],
 ['349', '0', '400', '3.359999895', '2'],
 ['350', '0', '620', '2.849999905', '2'],
 ['351', '1', '780', '4', '2'],
 ['352', '0', '620', '3.430000067', '3'],
 ['353', '1', '580', '3.119999886', '3'],
 ['354', '0', '700', '3.519999981', '2'],
 ['355', '1', '540', '3.779999971', '2'],
 ['356', '1', '760', '2.809999943', '1'],
 ['357', '0', '700', '3.269999981', '2'],
 ['358', '0', '720', '3.309999943', '1'],
 ['359', '1', '560', '3.690000057', '3'],
 ['360', '0', '720', '3.940000057', '3'],
 ['361', '1', '520', '4', '1'],
 ['362', '1', '540', '3.49000001', '1'],
 ['363', '0', '680', '3.140000105', '2'],
 ['364', '0', '460', '3.440000057', '2'],
 ['365', '1', '560', '3.359999895', '1'],
 ['366', '0', '480', '2.779999971', '3'],
 ['367', '0', '460', '2.930000067', '3'],
 ['368', '0', '620', '3.630000114', '3'],
 ['369', '0', '580', '4', '1'],
 ['370', '0', '800', '3.890000105', '2'],
 ['371', '1', '540', '3.769999981', '2'],
 ['372', '1', '680', '3.75999999', '3'],
 ['373', '1', '680', '2.420000076', '1'],
 ['374', '1', '620', '3.369999886', '1'],
 ['375', '0', '560', '3.779999971', '2'],
 ['376', '0', '560', '3.49000001', '4'],
 ['377', '0', '620', '3.630000114', '2'],
 ['378', '1', '800', '4', '2'],
 ['379', '0', '640', '3.119999886', '3'],
 ['380', '0', '540', '2.700000048', '2'],
 ['381', '0', '700', '3.650000095', '2'],
 ['382', '1', '540', '3.49000001', '2'],
 ['383', '0', '540', '3.50999999', '2'],
 ['384', '0', '660', '4', '1'],
 ['385', '1', '480', '2.619999886', '2'],
 ['386', '0', '420', '3.019999981', '1'],
 ['387', '1', '740', '3.859999895', '2'],
 ['388', '0', '580', '3.359999895', '2'],
 ['389', '0', '640', '3.170000076', '2'],
 ['390', '0', '640', '3.50999999', '2'],
 ['391', '1', '800', '3.049999952', '2'],
 ['392', '1', '660', '3.880000114', '2'],
 ['393', '1', '600', '3.380000114', '3'],
 ['394', '1', '620', '3.75', '2'],
 ['395', '1', '460', '3.99000001', '3'],
 ['396', '0', '620', '4', '2'],
 ['397', '0', '560', '3.039999962', '3'],
 ['398', '0', '460', '2.630000114', '2'],
 ['399', '0', '700', '3.650000095', '2'],
 ['400', '0', '600', '3.890000105', '3']]

In [42]:
import sys
sys._enablelegacywindowsfsencoding()
df = pd.read_csv(filename)

In [43]:
df.head()

   obs  admit  gre   gpa  rank
0    1      0  380  3.61     3
1    2      1  660  3.67     3
2    3      1  800  4.00     1
3    4      1  640  3.19     4
4    5      0  520  2.93     4

In [49]:
df.describe()

              obs       admit         gre         gpa       rank
count  400.000000  400.000000  400.000000  400.000000  400.00000
mean   200.500000    0.317500  587.700000    3.389900    2.48500
std    115.614301    0.466087  115.516536    0.380567    0.94446
min      1.000000    0.000000  220.000000    2.260000    1.00000
25%    100.750000    0.000000  520.000000    3.130000    2.00000
50%    200.500000    0.000000  580.000000    3.395000    2.00000
75%    300.250000    1.000000  660.000000    3.670000    3.00000
max    400.000000    1.000000  800.000000    4.000000    4.00000

In [48]:
pd.crosstab(df['admit'], df['rank'])

rank    1   2   3   4
admit
0      28  97  93  55
1      33  54  28  12

In [12]:
ranks = pd.get_dummies(df['rank'])

In [13]:
ranks.head()

   1  2  3  4
0  0  0  1  0
1  0  0  1  0
2  1  0  0  0
3  0  0  0  1
4  0  0  0  1

In [71]:
X = pd.concat([df[['gre', 'gpa']], ranks], axis=1)
X1 = df[['gre', 'gpa', 'rank']]
# X = df[['gre', 'gpa']]

y = df['admit']

In [72]:
X[:3]

   gre   gpa  1  2  3  4
0  380  3.61  0  0  1  0
1  660  3.67  0  0  1  0
2  800  4.00  1  0  0  0

In [73]:
X.shape

(400, 6)

In [74]:
y[:3]

0    0
1    1
2    1
Name: admit, dtype: int64

In [75]:
from sklearn.feature_selection import chi2

In [76]:
scores, pvalues = chi2(X, y)
print(['{:.6f}'.format(score) for score in scores])
print(['{:.6f}'.format(pvalue) for pvalue in pvalues])

['308.168893', '0.541406', '14.059659', '1.121408', '4.138998', '5.922056']
['0.000000', '0.461851', '0.000177', '0.289616', '0.041906', '0.014953']

In [125]:
from sklearn.linear_model import LogisticRegression, RidgeClassifier, SGDClassifier

reg = LogisticRegression(C=1.)
reg1 = LogisticRegression(C=10000)
X_train, y_train, X_test, y_test = X[:-100], y[:-100], X[-100:], y[-100:]
clf = reg.fit(X_train, y_train)
clf1 = reg1.fit(X1, y)

In [126]:
print(clf.intercept_)
print(clf.coef_)

[-1.92924285]
[[ 0.00224727  0.08440538  0.43527501 -0.25466615 -0.98484773 -1.12500399]]

In [127]:
print(clf1.intercept_)
print(clf1.coef_)

[-3.4178049]
[[ 0.00227524  0.77041473 -0.55881557]]

In [128]:
from sklearn.metrics import accuracy_score

y_ = clf.predict(X_test)
accuracy_score(y_, y_test)

0.68

In [129]:
y1_ = clf1.predict(X1)
accuracy_score(y1_, y)

0.705

In [135]:
ridge = RidgeClassifier()
clfr = ridge.fit(X_train, y_train)
yr_ = clfr.predict(X_test)
accuracy_score(yr_, y_test)

0.69

In [133]:
sgd = SGDClassifier(loss='log')
clfs = sgd.fit(X_train, y_train)
ys_ = clfs.predict(X_test)
accuracy_score(ys_, y_test)

D:\Users\25052288840\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)

0.35

In [150]:
from sklearn.feature_selection import f_regression
fs, ps = f_regression(X, y)
fs = ['{:.5f}'.format(f) for f in fs]
ps = ['{:.5f}'.format(p) for p in ps]
print('f-values: %s' % fs)
print('p-values: %s' % ps)

f-values: ['14.01511', '13.05495', '17.22084', '1.80056', '5.99329', '7.20617']
p-values: ['0.00021', '0.00034', '0.00004', '0.18041', '0.01479', '0.00757']